version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
    - ./volumes/mysql/:/var/lib/mysql
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
    - mysql_network
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: passroot
      MYSQL_DATABASE: dashboard

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    restart: always
    networks:
    - mysql_network
    ports:
    - 8890:80
    environment:
        PMA_HOST: mysql

  api:
    build: "api"
    image: "api"
    ports:
      - "8081:8081"
    networks:
      - dashboard_network
      - mysql_network
    volumes:
      - ./api/:/src
    tty: true
    environment:
      DATABASE_ROOT_USERNAME: 'root'
      DATABASE_ROOT_PASSWORD: 'passroot'
      DATABASE_HOST: 'mysql'
      DATABASE_PORT: 3306

  front:
    build: "front"
    image: "front"
    ports:
      - "8080:3000"
    networks:
      - dashboard_network
    tty: true
    environment:
      REACT_APP_API_URL: "http://localhost:8081"
      MICROSOFT_APP_ID: "0e63e88d-d336-4428-8782-2b7d7dd386e7"
      MICROSOFT_APP_SECRETVALUE: "Bs2~nV1cos0b_K5fl737y9cG-Gs_Cm_cYs"
    volumes:
      - ./front/:/app

networks:
  dashboard_network:
  mysql_network:
